#!/usr/bin/env bash
# Define the new IP addresses
NEW_LOCALHOST_IP="127.0.0.2"
NEW_FACEBOOK_IP="8.8.8.8"

# Edit /etc/hosts to set new IP addresses
sudo sed -i "s/^127.0.0.1[[:space:]]localhost$/127.0.0.1 localhost\n$NEW_LOCALHOST_IP localhost/g" /etc/hosts
sudo sed -i "s/^8.8.8.8[[:space:]]facebook.com$/8.8.8.8 facebook.com/g" /etc/hosts

