#!/usr/bin/env bash

# Generate RSA key pair with 4096 bits and passphrase
ssh-keygen -t rsa -b 4096 -C "school" -f ~/.ssh/school -N "betty"

# Configure SSH client to use the private key and refuse password authentication
echo "IdentityFile ~/.ssh/school" >> ~/.ssh/config
echo "PasswordAuthentication no" >> ~/.ssh/config
