#!/usr/bin/env bash

# Generate RSA key pair with 4096 bits and passphrase
openssl genrsa -aes256 -out ~/.ssh/school.pem 4096

# Configure SSH client to use the private key and refuse password authentication
echo "IdentityFile ~/.ssh/school.pem" >> ~/.ssh/config
echo "PasswordAuthentication no" >> ~/.ssh/config

